const Props: {
  props: any,
  excludes: string[]
} = {
  props: {
    '$abbr': 'attr.abbr',
    '$accept': 'attr.accept',
    '$acceptCharset': 'attr.accept-charset',
    '$accessKey': 'attr.accesskey',
    '$action': 'attr.action',
    '$alink': 'attr.alink',
    '$allow': 'attr.allow',
    '$allowFullscreen': 'attr.allowfullscreen',
    '$allowPaymentRequest': 'attr.allowpaymentrequest',
    '$allowUserMedia': 'attr.allowusermedia',
    '$alt': 'attr.alt',
    '$archive': 'attr.archive',
    '$as': 'attr.as',
    '$async': 'attr.async',
    '$attrHeight': 'attr.height',
    '$attrWidth': 'attr.width',
    '$autoCapitalize': 'attr.autocapitalize',
    '$autoComplete': 'atrr.autocomplete',
    '$autoFocus': 'attr.autofocus',
    '$autoPlay': 'attr.autoplay',
    '$axis': 'attr.axis',
    '$capture': 'attr.capture',
    '$cellPadding': 'attr.cellpadding',
    '$cellSpacing': 'attr.cellspacing',
    '$char': 'attr.char',
    '$charOff': 'attr.charoff',
    '$charset': 'attr.charset',
    '$checked': 'attr.checked',
    '$cite': 'attr.cite',
    '$classId': 'attr.classid',
    '$className': 'attr.class',
    '$clearAttr': 'attr.clear',
    '$code': 'attr.code',
    '$codeBase': 'attr.codebase',
    '$codeType': 'attr.codetype',
    '$cols': 'attr.cols',
    '$colSpan': 'attr.colspan',
    '$compact': 'attr.compact',
    '$contentEditable': 'attr.contenteditable',
    '$controls': 'attr.controls',
    '$coords': 'attr.coords',
    '$crossOrigin': 'attr.crossorigin',
    '$d': 'attr.d',
    '$data': 'attr.data',
    '$datetime': 'attr.datetime',
    '$declare': 'attr.declare',
    '$decoding': 'attr.decoding',
    '$dir': 'attr.dir',
    '$dirname': 'attr.dirname',
    '$disabled': 'attr.disabled',
    '$download': 'attr.download',
    '$draggable': 'attr.draggable',
    '$enctype': 'attr.enctype',
    '$enterKeyHint': 'attr.enterkeyhint',
    '$fill': 'attr.fill',
    '$form': 'attr.form',
    '$formAction': 'attr.formaction',
    '$formEnctype': 'attr.formenctype',
    '$formMethod': 'attr.formmethod',
    '$formNoValidate': 'attr.formnovalidate',
    '$formTarget': 'attr.formtarget',
    '$frame': 'attr.frame',
    '$frameBorder': 'attr.frameborder',
    '$headers': 'attr.headers',
    '$hidden': 'attr.hidden',
    '$high': 'attr.high',
    '$href': 'attr.href',
    '$hrefLang': 'attr.hreflang',
    '$hSpace': 'attr.hspace',
    '$id': 'attr.id',
    '$imageSizes': 'attr.imagesizes',
    '$imageSrcSet': 'attr.imagesrcset',
    '$inputMode': 'attr.inputmode',
    '$integrity': 'attr.integrity',
    '$is': 'attr.is',
    '$isMap': 'attr.ismap',
    '$itemId': 'attr.itemid',
    '$itemProp': 'attr.itemprop',
    '$itemRef': 'attr.itemref',
    '$itemScope': 'attr.itemscope',
    '$itemType': 'attr.itemtype',
    '$kind': 'attr.kind',
    '$label': 'attr.label',
    '$lang': 'attr.lang',
    '$link': 'attr.link',
    '$list': 'attr.list',
    '$longDesc': 'attr.longdesc',
    '$loop': 'attr.loop',
    '$low': 'attr.low',
    '$marginHeight': 'attr.marginheight',
    '$marginWidth': 'attr.marginwidth',
    '$max': 'attr.max',
    '$maxLength': 'attr.maxlength',
    '$media': 'attr.media',
    '$method': 'attr.method',
    '$min': 'attr.min',
    '$minLength': 'attr.minlength',
    '$multiple': 'attr.multiple',
    '$muted': 'attr.muted',
    '$attrName': 'attr.name',
    '$nonce': 'attr.nonce',
    '$noResize': 'attr.noresize',
    '$noShade': 'attr.noshade',
    '$noValidate': 'attr.novalidate',
    '$noWrap': 'attr.nowrap',
    '$object': 'attr.object',
    '$open': 'attr.open',
    '$optimum': 'attr.optimum',
    '$pattern': 'attr.pattern',
    '$ping': 'attr.ping',
    '$placeholder': 'attr.placeholder',
    '$playsInline': 'attr.playsinline',
    '$poster': 'attr.poster',
    '$preload': 'attr.preload',
    '$preserveAspectRatio': 'attr.preserveAspectRatio',
    '$profile': 'attr.profile',
    '$prompt': 'attr.prompt',
    '$readOnly': 'attr.readonly',
    '$referrerPolicy': 'attr.referrerpolicy',
    '$rel': 'attr.rel',
    '$required': 'attr.required',
    '$rev': 'attr.rev',
    '$reversed': 'attr.reversed',
    '$rows': 'attr.rows',
    '$rowSpan': 'attr.rowspan',
    '$sandBox': 'attr.sandbox',
    '$scope': 'attr.scope',
    '$scrolling': 'attr.scrolling',
    '$selected': 'attr.selected',
    '$shape': 'attr.shape',
    '$sizes': 'attr.sizes',
    '$slot': 'attr.slot',
    '$span': 'attr.span',
    '$spellCheck': 'attr.spellcheck',
    '$src': 'attr.src',
    '$srcDoc': 'attr.srcdoc',
    '$srcSet': 'attr.srcset',
    '$standBy': 'attr.standby',
    '$start': 'attr.start',
    '$step': 'attr.step',
    '$summary': 'attr.summary',
    '$tabIndex': 'attr.tabindex',
    '$target': 'attr.target',
    '$title': 'attr.title',
    '$translate': 'attr.translate',
    '$attrTransform': 'attr.transform',
    '$type': 'attr.type',
    '$typeMustMatch': 'attr.typemustmatch',
    '$useMap': 'attr.usemap',
    '$vAlign': 'attr.valign',
    '$value': 'attr.value',
    '$valueType': 'attr.valuetype',
    '$viewBox': 'attr.viewBox',
    '$vLink': 'attr.vlink',
    '$vSpace': 'attr.vspace',
    '$wrap': 'attr.wrap',
    '$xmlns': 'attr.xmlns',
    'className': 'attr.class',
    '$attrDefault': 'attr.default',
    '$attrFor': 'attr.for',
    '$for': 'attr.for',
    '$default': 'attr.default'
  },
  excludes: [
    '$native',
    '$children',
    '$level',
    '$model',
    '$tagName',
    '$pseudo',
    '$global',
    '$hostComponent',
    '$root',
    '$node',
    '$loadQueue',
    '$nid',
    'id',
    'tagName',
    '$animation',
    '$rules',
    'cssRules',
    'options',
    '$events',
    'root',
    'value',
    'get',
    'set',

    // states
    '$stackVertical',
    '$childVerticalSpacing',
    '$size',
    '$absPosition',
    '$absCenter',
    '$absCenterRight',
    '$absCenterLeft',
    '$absCenterTop',
    '$absCenterBottom',
    '$absTopRight',
    '$absTopLeft',
    '$absBottomRight',
    '$absBottomLeft',
    '$absCenterVertical',
    '$absCenterHorizontal',
    '$aspectRation',
    '$truncateText',
    '$relCenterHorizontal',
    '$clearFix',
    '$backgroundGradient',
    '$flexSpaceBetween',
    '$flexCenter',
    '$responsiveness',
    '$styles',
    '$medias'
  ]
}


export default Props;
