const Props: {
  props: any,
  excludes: string[]
} = {
  props: {
    '$attrAbbr': 'attr.abbr',
    '$attrAcceptCharset': 'attr.accept-charset',
    '$attrAccept': 'attr.accept',
    '$attrAccesskey': 'attr.accesskey',
    '$attrAction': 'attr.action',
    '$attrAlign': 'attr.align',
    '$attrAlink': 'attr.alink',
    '$attrAllow': 'attr.allow',
    '$attrAllowfullscreen': 'attr.allowfullscreen',
    '$attrAllowpaymentrequest': 'attr.allowpaymentrequest',
    '$attrAlt': 'attr.alt',
    '$attrArchive': 'attr.archive',
    '$attrAsync': 'attr.async',
    '$attrAutobuffer': 'attr.autobuffer',
    '$attrAutocapitalize': 'attr.autocapitalize',
    '$attrAutocomplete': 'attr.autocomplete',
    '$attrAutofocus': 'attr.autofocus',
    '$attrAutoplay': 'attr.autoplay',
    '$attrAxis': 'attr.axis',
    '$attrBackground': 'attr.background',
    '$attrBehavior': 'attr.behavior',
    '$attrBgcolor': 'attr.bgcolor',
    '$attrBorder': 'attr.border',
    '$attrBottommargin': 'attr.bottommargin',
    '$attrCapture': 'attr.capture',
    '$attrCellpadding': 'attr.cellpadding',
    '$attrCellspacing': 'attr.cellspacing',
    '$attrChar': 'attr.char',
    '$attrCharoff': 'attr.charoff',
    '$attrCharset': 'attr.charset',
    '$attrChecked': 'attr.checked',
    '$attrCite': 'attr.cite',
    '$className': 'attr.class',
    '$attrClassid': 'attr.classid',
    '$attrClear': 'attr.clear',
    '$attrCode': 'attr.code',
    '$attrCodebase': 'attr.codebase',
    '$attrCodetype': 'attr.codetype',
    '$attrColor': 'attr.color',
    '$attrCols': 'attr.cols',
    '$attrColspan': 'attr.colspan',
    '$attrCommand': 'attr.command',
    '$attrCompact': 'attr.compact',
    '$attrContent': 'attr.content',
    '$attrContenteditable': 'attr.contenteditable',
    '$attrContextmenu': 'attr.contextmenu',
    '$attrControls': 'attr.controls',
    '$attrCoords': 'attr.coords',
    '$attrCrossorigin': 'attr.crossorigin',
    '$attrData': 'attr.data',
    '$attrDatafld': 'attr.datafld',
    '$attrDatasrc': 'attr.datasrc',
    '$attrDatetime': 'attr.datetime',
    '$attrDeclare': 'attr.declare',
    '$attrDecoding': 'attr.decoding',
    '$attrDefault': 'attr.default',
    '$attrDefer': 'attr.defer',
    '$attrDir': 'attr.dir',
    '$attrDirection': 'attr.direction',
    '$attrDirname': 'attr.dirname',
    '$attrDisabled': 'attr.disabled',
    '$attrDownload': 'attr.download',
    '$attrDraggable': 'attr.draggable',
    '$attrEnctype': 'attr.enctype',
    '$attrEnterkeyhint': 'attr.enterkeyhint',
    '$attrExportparts': 'attr.exportparts',
    '$attrFace': 'attr.face',
    '$attrFetchpriority': 'attr.fetchpriority',
    '$attrFor': 'attr.for',
    '$attrForm': 'attr.form',
    '$attrFormaction': 'attr.formaction',
    '$attrFormenctype': 'attr.formenctype',
    '$attrFormmethod': 'attr.formmethod',
    '$attrFormnovalidate': 'attr.formnovalidate',
    '$attrFormtarget': 'attr.formtarget',
    '$attrFrame': 'attr.frame',
    '$attrFrameborder': 'attr.frameborder',
    '$attrHeaders': 'attr.headers',
    '$attrHeight': 'attr.height',
    '$attrHidden': 'attr.hidden',
    '$attrHigh': 'attr.high',
    '$attrHref': 'attr.href',
    '$attrHreflang': 'attr.hreflang',
    '$attrHspace': 'attr.hspace',
    '$attrHttpEquiv': 'attr.http-equiv',
    '$attrIcon': 'attr.icon',
    '$attrId': 'attr.id',
    '$attrImagesizes': 'attr.imagesizes',
    '$attrImagesrcset': 'attr.imagesrcset',
    '$attrInert': 'attr.inert',
    '$attrInputmode': 'attr.inputmode',
    '$attrIntegrity': 'attr.integrity',
    '$attrIs': 'attr.is',
    '$attrIsmap': 'attr.ismap',
    '$attrItemid': 'attr.itemid',
    '$attrItemprop': 'attr.itemprop',
    '$attrItemref': 'attr.itemref',
    '$attrItemscope': 'attr.itemscope',
    '$attrItemtype': 'attr.itemtype',
    '$attrKind': 'attr.kind',
    '$attrLabel': 'attr.label',
    '$attrLang': 'attr.lang',
    '$attrLanguage': 'attr.language',
    '$attrLeftmargin': 'attr.leftmargin',
    '$attrLink': 'attr.link',
    '$attrList': 'attr.list',
    '$attrLoading': 'attr.loading',
    '$attrLongdesc': 'attr.longdesc',
    '$attrLoop': 'attr.loop',
    '$attrLow': 'attr.low',
    '$attrManifest': 'attr.manifest',
    '$attrMarginheight': 'attr.marginheight',
    '$attrMarginwidth': 'attr.marginwidth',
    '$attrMax': 'attr.max',
    '$attrMaxlength': 'attr.maxlength',
    '$attrMayscript': 'attr.mayscript',
    '$attrMedia': 'attr.media',
    '$attrMethod': 'attr.method',
    '$attrMethods': 'attr.methods',
    '$attrMin': 'attr.min',
    '$attrMinlength': 'attr.minlength',
    '$attrMozOpaque': 'attr.moz-opaque',
    '$attrMozallowfullscreen': 'attr.mozallowfullscreen',
    '$attrMsallowfullscreen': 'attr.msallowfullscreen',
    '$attrMultiple': 'attr.multiple',
    '$attrMuted': 'attr.muted',
    '$attrName': 'attr.name',
    '$attrNohref': 'attr.nohref',
    '$attrNomodule': 'attr.nomodule',
    '$attrNonce': 'attr.nonce',
    '$attrNoresize': 'attr.noresize',
    '$attrNoshade': 'attr.noshade',
    '$attrNovalidate': 'attr.novalidate',
    '$attrNowrap': 'attr.nowrap',
    '$attrObject': 'attr.object',
    '$attrOnerror': 'attr.onerror',
    '$attrOpen': 'attr.open',
    '$attrOptimum': 'attr.optimum',
    '$attrPart': 'attr.part',
    '$attrPattern': 'attr.pattern',
    '$attrPing': 'attr.ping',
    '$attrPlaceholder': 'attr.placeholder',
    '$attrPoster': 'attr.poster',
    '$attrPrefetch': 'attr.prefetch',
    '$attrPreload': 'attr.preload',
    '$attrPreserveAspectRatio': 'attr.preserveAspectRatio',
    '$attrProfile': 'attr.profile',
    '$attrRadiogroup': 'attr.radiogroup',
    '$attrReadonly': 'attr.readonly',
    '$attrReferrerpolicy': 'attr.referrerpolicy',
    '$attrRel': 'attr.rel',
    '$attrRequired': 'attr.required',
    '$attrRev': 'attr.rev',
    '$attrReversed': 'attr.reversed',
    '$attrRightmargin': 'attr.rightmargin',
    '$attrRows': 'attr.rows',
    '$attrRowspan': 'attr.rowspan',
    '$attrRules': 'attr.rules',
    '$attrSandboxAllowDownloads': 'attr.sandbox-allow-downloads',
    '$attrSandboxAllowModals': 'attr.sandbox-allow-modals',
    '$attrSandboxAllowPopupsToEscapeSandbox': 'attr.sandbox-allow-popups-to-escape-sandbox',
    '$attrSandboxAllowPopups': 'attr.sandbox-allow-popups',
    '$attrSandboxAllowPresentation': 'attr.sandbox-allow-presentation',
    '$attrSandboxAllowSameOrigin': 'attr.sandbox-allow-same-origin',
    '$attrSandboxAllowStorageAccessByUserActivation': 'attr.sandbox-allow-storage-access-by-user-activation',
    '$attrSandboxAllowTopNavigationByUserActivation': 'attr.sandbox-allow-top-navigation-by-user-activation',
    '$attrSandbox': 'attr.sandbox',
    '$attrScope': 'attr.scope',
    '$attrScrollamount': 'attr.scrollamount',
    '$attrScrolldelay': 'attr.scrolldelay',
    '$attrScrolling': 'attr.scrolling',
    '$attrSelected': 'attr.selected',
    '$attrShadowroot': 'attr.shadowroot',
    '$attrShape': 'attr.shape',
    '$attrSize': 'attr.size',
    '$attrSizes': 'attr.sizes',
    '$attrSlot': 'attr.slot',
    '$attrSpan': 'attr.span',
    '$attrSpellcheck': 'attr.spellcheck',
    '$attrSrc': 'attr.src',
    '$attrSrcdoc': 'attr.srcdoc',
    '$attrSrclang': 'attr.srclang',
    '$attrSrcset': 'attr.srcset',
    '$attrStandby': 'attr.standby',
    '$attrStart': 'attr.start',
    '$attrStep': 'attr.step',
    '$attrStyle': 'attr.style',
    '$attrSummary': 'attr.summary',
    '$attrTabindex': 'attr.tabindex',
    '$attrTarget': 'attr.target',
    '$attrText': 'attr.text',
    '$attrTitle': 'attr.title',
    '$attrTopmargin': 'attr.topmargin',
    '$attrTranslate': 'attr.translate',
    '$attrTruespeed': 'attr.truespeed',
    '$attrType': 'attr.type',
    '$attrUsemap': 'attr.usemap',
    '$attrValign': 'attr.valign',
    '$attrValue': 'attr.value',
    '$attrValuetype': 'attr.valuetype',
    '$attrVersion': 'attr.version',
    '$attrViewbox': 'attr.viewBox',
    '$attrVlink': 'attr.vlink',
    '$attrVspace': 'attr.vspace',
    '$attrWebkitallowfullscreen': 'attr.webkitallowfullscreen',
    '$attrWidth': 'attr.width',
    '$attrWrap': 'attr.wrap',
    '$attrXMozErrormessage': 'attr.x-moz-errormessage',
    '$attrXmlns': 'attr.xmlns'
  },
  excludes: [
    '$native',
    '$children',
    '$level',
    '$model',
    '$tagName',
    '$className',
    '$pseudo',
    '$global',
    '$style',
    '$media',
    '$hostComponent',
    '$root',
    '$node',
    '$loadQueue',
    '$nid',
    'id',
    'tagName',
    '$animation',
    '$rules',
    'cssRules',
    'options',
    '$events',
    'root',
    'value',
    'get',
    'set'
  ]
}


export default Props;
